version: "3.8"

services:
  client:
    image: ghcr.io/ucsb-cs148-w25/pj04-restaurantdecider/pj04-restaurantdecider-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "2500:5173"
    environment:
      - NODE_ENV=production
      - PORT=5173
      - HOST=0.0.0.0
    depends_on:
      - server

  server:
    image: ghcr.io/ucsb-cs148-w25/pj04-restaurantdecider/pj04-restaurantdecider-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "2530:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./server/data:/usr/src/app/data
