version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "2500:5173"
    environment:
      - NODE_ENV=production
      - PORT=5173
      - HOST=0.0.0.0
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "2530:3000"
      - "2531:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./server/data:/usr/src/app/data
